services:
  - type: web
    name: application-rationalization-tool
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 120 --workers 2 web.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATA_PATH
        value: ./data
    healthCheckPath: /
